FROM node:alpine3.11

WORKDIR /src

# To use packages in CLI without global install
ENV PATH /src/node_modules/.bin:$PATH

COPY ./ ./

RUN npm install --silent

ENV GIT_WORK_TREE=/src GIT_DIR=/app/.git

RUN apk update && \
    apk add git

CMD ["/bin/sh", "-c", "jest --watch"]