module.exports = {
	apps: {
		web: {
			NEXT_PUBLIC_IS_DEV: true,
			SENTRY_IGNORE_API_RESOLUTION_ERROR:
				process.env.SENTRY_IGNORE_API_RESOLUTION_ERROR,
			NEXT_PUBLIC_IS_DEV: process.env.NEXT_PUBLIC_IS_DEV,
			DATABASE_URL: process.env.DATABASE_URL,
			NEXT_PUBLIC_SOCKET_HOST: process.env.NEXT_PUBLIC_SOCKET_HOST,
			NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST:
				process.env.NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST,
			NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
				process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
			STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
			SUBSCRIPTION_PRICE_ID: process.env.SUBSCRIPTION_PRICE_ID,
			TWITCH_CLIENT_ID: process.env.TWITCH_CLIENT_ID,
			TWITCH_SECRET: process.env.TWITCH_SECRET,
			ADS_DISABLED: process.env.ADS_DISABLED,
			NEXT_PUBLIC_API_KEY: process.env.NEXT_PUBLIC_API_KEY,
			NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
			FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL,
			NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
			NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:
				process.env.FIREBASE_MESSAGING_SENDER_ID,
			NEXT_PUBLIC_FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
			NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: process.env.FIREBASE_MEASUREMENT_ID
		}
	},
	packages: {
		prisma: {
			DATABASE_URL: process.env.DATABASE_URL
		}
	}
}
