import mongoose from "mongoose";

const raw = [
  {
    _id: "60da97598821ed46dc9c008c",
    displayName: "Warzone",
    backgroundImage: "/warzone/background-image.png",
    titleImage: "/warzone/title-image.png",
    __v: 0,
    active: true,
    urlSafeName: "warzone",
    blurDataURL: "/media/games/warzone/placeholder-image.png",
    developer: "Activision",
    genres: ["Battle Royale", "FPS"],
    platforms: ["PC", "PS4", "X Box"],
    releaseDate: "2020-03-10T12:00:00Z",
  },
  {
    _id: "60dba9d19abd9755b002cea8",
    meta: {},
    active: false,
    displayName: "Dota 2",
    backgroundImage: "/dota/background-image.jpg",
    titleImage: "/dota/title-image.png",
    __v: 0,
    blurDataURL: "/media/games/dota/placeholder-image.png",
    developer: "Valve Corporation",
    genres: ["MOBA"],
    platforms: ["PC", "PS4", "X Box"],
    releaseDate: "2013-07-09T12:00:00Z",
    urlSafeName: "dota",
  },
  {
    _id: "60dbb2189abd9755b002ceb5",
    meta: {},
    active: false,
    displayName: "League of Legends",
    backgroundImage: "/league-of-legends/background-image.jpg",
    titleImage: "/league-of-legends/title-image.png",
    __v: 0,
    blurDataURL: "media/games/league-of-legends/placeholder-image.png",
    developer: "Riot Games",
    genres: ["MOBA"],
    platforms: ["PC"],
    releaseDate: "2009-10-27T12:00:00Z",
    urlSafeName: "league",
  },
  {
    _id: "60dbb2b29abd9755b002ceba",
    meta: {},
    active: false,
    displayName: "Escape from Tarkov",
    backgroundImage: "/tarkov/background-image.jpg",
    titleImage: "/tarkov/title-image.png",
    __v: 0,
    blurDataURL: "/media/games/tarkov/placeholder-image.png",
    developer: "Battlestate Games",
    genres: ["FPS", "Survival"],
    platforms: ["PC"],
    releaseDate: "2009-07-27T12:00:00Z",
    urlSafeName: "tarkov",
  },
];

export default raw.map((game) => ({
  ...game,
  releaseDate: new Date(game.releaseDate),
  _id: new mongoose.Types.ObjectId(game._id),
}));
