module.exports = {
	extends: ["next", "prettier"],
	rules: {
		"@next/next/no-html-link-for-pages": "off",
		"array-bracket-spacing": "error",
		"array-callback-return": "error",
		"arrow-body-style": "error",
		"arrow-parens": "error",
		"arrow-spacing": "error",
		"block-spacing": "error",
		"brace-style": "error",
		"camelcase": "error",
		"comma-dangle": ["error", "never"],
		"comma-spacing": "error",
		"computed-property-spacing": "error",
		"default-param-last": "error",
		"dot-notation": "error",
		"eol-last": ["error", "always"],
		"eqeqeq": "error",
		"func-call-spacing": "error",
		"func-style": "error",
		"function-paren-newline": "error",
		"implicit-arrow-linebreak": "error",
		"import/first": "error",
		"import/no-anonymous-default-export": "off",
		"import/no-mutable-exports": "error",
		"key-spacing": "error",
		"keyword-spacing": "error",
		"max-len": ["error", { code: 80 }],
		"newline-per-chained-call": "error",
		"no-case-declarations": "error",
		"no-confusing-arrow": "error",
		"no-duplicate-imports": "error",
		"no-else-return": "error",
		"no-eval": "error",
		"no-loop-func": "error",
		"no-mixed-operators": "error",
		"no-multi-assign": "error",
		"no-multiple-empty-lines": "error",
		"no-nested-ternary": "error",
		"no-new-func": "error",
		"no-param-reassign": "error",
		"no-prototype-builtins": "error",
		"no-restricted-globals": "error",
		"no-trailing-spaces": "error",
		"no-unneeded-ternary": "error",
		"no-unused-vars": "error",
		"no-unused-vars": 1,
		"no-useless-constructor": "error",
		"no-useless-escape": "error",
		"no-whitespace-before-property": "error",
		"nonblock-statement-body-position": "error",
		"object-curly-newline": "error",
		"object-shorthand": ["error", "always"],
		"one-var": 0,
		"operator-linebreak": "error",
		"padded-blocks": 0,
		"prefer-arrow-callback": "error",
		"prefer-const": "error",
		"prefer-object-spread": "error",
		"prefer-rest-params": "error",
		"prefer-spread": "error",
		"quote-props": ["error", "consistent-as-needed"],
		"quotes": ["error", "double"],
		"react/jsx-key": "off",
		"react/no-unescaped-entities": "error",
		"semi": ["error", "never"],
		"space-before-blocks": "error",
		"space-before-blocks": "error",
		"space-before-function-paren": "error",
		"space-in-parens": "error",
		"space-infix-ops": "error",
		"wrap-iife": "error"
	}
}
