module.exports = {
	extends: ["next", "prettier"],
	rules: {
		"@next/next/no-html-link-for-pages": "off",
		"array-bracket-spacing": "warn",
		"array-callback-return": "warn",
		"arrow-body-style": "warn",
		"arrow-parens": "warn",
		"arrow-spacing": "warn",
		"block-spacing": "warn",
		"brace-style": "warn",
		"camelcase": "warn",
		"comma-dangle": ["warn", "never"],
		"comma-spacing": "warn",
		"computed-property-spacing": "warn",
		"default-param-last": "warn",
		"dot-notation": "warn",
		"eol-last": ["warn", "always"],
		"eqeqeq": "warn",
		"func-call-spacing": "warn",
		"func-style": "warn",
		"function-paren-newline": "warn",
		"implicit-arrow-linebreak": "warn",
		"import/extensions": "warn",
		"import/first": "warn",
		"import/no-anonymous-default-export": "off",
		"import/no-mutable-exports": "warn",
		"key-spacing": "warn",
		"keyword-spacing": "warn",
		"max-len": ["warn", { code: 80 }],
		"newline-per-chained-call": "warn",
		"no-case-declarations": "warn",
		"no-confusing-arrow": "warn",
		"no-duplicate-imports": "warn",
		"no-else-return": "warn",
		"no-eval": "warn",
		"no-loop-func": "warn",
		"no-mixed-operators": "warn",
		"no-multi-assign": "warn",
		"no-multiple-empty-lines": "warn",
		"no-nested-ternary": "warn",
		"no-new-func": "warn",
		"no-param-reassign": "warn",
		"no-prototype-builtins": "warn",
		"no-restricted-globals": "warn",
		"no-trailing-spaces": "warn",
		"no-unneeded-ternary": "warn",
		"no-unused-vars": "warn",
		"no-unused-vars": 1,
		"no-useless-constructor": "warn",
		"no-useless-escape": "warn",
		"no-whitespace-before-property": "warn",
		"nonblock-statement-body-position": "warn",
		"object-curly-newline": "warn",
		"object-shorthand": ["warn", "always"],
		"one-var": 0,
		"operator-linebreak": "warn",
		"padded-blocks": 0,
		"prefer-arrow-callback": "warn",
		"prefer-const": "warn",
		"prefer-object-spread": "warn",
		"prefer-rest-params": "warn",
		"prefer-spread": "warn",
		"quote-props": ["warn", "consistent-as-needed"],
		"quotes": ["warn", "double"],
		"react/jsx-key": "off",
		"react/no-unescaped-entities": "warn",
		"semi": ["warn", "never"],
		"space-before-blocks": "warn",
		"space-before-blocks": "warn",
		"space-before-function-paren": "warn",
		"space-in-parens": "warn",
		"space-infix-ops": "warn",
		"spaced-comment": "warn",
		"wrap-iife": "warn"
	}
}
