name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  build-and-unit-test:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}

      - name: Install dependencies
        run: yarn install

      - name: Migrate DB
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
        run: cd packages/prisma && npx prisma migrate deploy

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
            directory: ./apps/web
            file_name: .env
            envkey_DB_CONNECTION_STRING: ${{secrets.DB_CONNECTION_STRING}}
            envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
            envkey_NEXT_PUBLIC_GOOGLE_ANALYTICS: ${{secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS}}
            envkey_NEXT_PUBLIC_API_KEY: ${{secrets.NEXT_PUBLIC_API_KEY}}
            envkey_NEXT_PUBLIC_FIREBASE_DATABASE_URL: ${{secrets.NEXT_PUBLIC_FIREBASE_DATABASE_URL}}
            envkey_FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
            envkey_FIREBASE_AUTH_DOMAIN: ${{secrets.FIREBASE_AUTH_DOMAIN}}
            envkey_FIREBASE_CLIENT_EMAIL: ${{secrets.FIREBASE_CLIENT_EMAIL}}
            envkey_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.FIREBASE_MESSAGING_SENDER_ID}}
            envkey_FIREBASE_APP_ID: ${{secrets.FIREBASE_APP_ID}}
            envkey_FIREBASE_MEASUREMENT_ID: ${{secrets.FIREBASE_MEASUREMENT_ID}}
            envkey_FIREBASE_COOKIE_SECRET_PREVIOUS: ${{secrets.FIREBASE_COOKIE_SECRET_PREVIOUS}}
            envkey_FIREBASE_COOKIE_SECRET_CURRENT: ${{secrets.FIREBASE_COOKIE_SECRET_CURRENT}}
            envkey_TWITCH_CLIENT_ID: ${{secrets.TWITCH_CLIENT_ID}}
            envkey_TWITCH_SECRET: ${{secrets.TWITCH_SECRET}}
            envkey_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}}
            envkey_STRIPE_SECRET_KEY: ${{secrets.STRIPE_SECRET_KEY}}
            envkey_STRIPE_WEBHOOK_SECRET: ${{secrets.STRIPE_WEBHOOK_SECRET}}
            envkey_SUBSCRIPTION_PRICE_ID: ${{secrets.SUBSCRIPTION_PRICE_ID}}
            envkey_MONTHLY_TIP_PRICE_ID: ${{secrets.MONTHLY_TIP_PRICE_ID}}
            envkey_NEXT_PUBLIC_SOCKET_HOST: ${{secrets.NEXT_PUBLIC_SOCKET_HOST}}
            envkey_GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
            envkey_NEXT_PUBLIC_SENTRY_DSN: ${{secrets.SENTRY_DSN}}
            envkey_SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
            envkey_SENTRY_LOG_LEVEL: debug

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push api image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: true
          tags: ghcr.io/${{github.repository}}/api-${{github.sha}}

      - name: Build and push web image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: true
          tags: ghcr.io/${{github.repository}}/web-${{github.sha}}

  deploy:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    needs: build-and-unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Trigger api deployment to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DOKKU_HOST}}
          username: ${{secrets.DOKKU_SSH_USER}}
          key: "${{ secrets.DOKKU_SSH_PRIVATE_KEY }}"
          script: |
           dokku git:from-image api ghcr.io/${{github.repository}}/api-${{github.sha}}

      - name: Trigger web deployment to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DOKKU_HOST}}
          username: ${{secrets.DOKKU_SSH_USER}}
          key: "${{ secrets.DOKKU_SSH_PRIVATE_KEY }}"
          script: |
           dokku git:from-image web ghcr.io/${{github.repository}}/web-${{github.sha}}