name: Playwright Testing
on:
  deployment_status:

env:
  FORCE_COLOR: 3
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  deploy-status-handler:
    name: 'Deploy Status Handler'
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Use deployment-status.environment as output
        id: deploy-handler
        run: echo "deployment_url=$(github.event.deployment_status.target_url)" >> $GITHUB_OUTPUT

  e2e-caller:
    uses: './.github/workflows/playwright-${{github.workflow.steps.deploy-handler.outputs.deployment_url}}.yml'
    with:
      deployment_url: ${{github.workflow.steps.deploy-handler.outputs.deployment_url}}
