name: Playwright Testing
on:
  deployment_status:

env:
  FORCE_COLOR: 3
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  deploy-status-handler:
    name: 'Deploy Status Handler'
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./tooling/github-actions/install

      - name: Logging
        run: echo '${{toJSON(github)}}'

      - name: Create tests for deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHA: ${{ github.sha }}
          REF: ${{ github.event.deployment.ref }}
        run: pnpm --filter @kittr/github-actions exec vite-node scripts/create-test-runs.ts
