name: Echo stuff
on:
  deployment_status:

env:
  FORCE_COLOR: 3
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Echo this
        run: echo ${{github.event}}

      - name: Echo that
        run: echo ${{github.event_name}}
