# If you're debugging E2Es, note that the workflow being ran is NOT the one in your PR.
# Due to limitations in GitHub Actions, the one on `main` is the one that is referenced for E2Es.
# You can find this codified in "./tooling/scripts/create-test-runs" in the `createWorkflowDispatch` call.

name: Playwright - design-react
on:
  workflow_dispatch:
    inputs:
      deployment_url:
        required: true
        type: string
      check_run_id:
        required: true
        type: string
      playwright_version:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.deployment_url }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  design-react:
    name: 'Design (React)'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v${{inputs.playwright_version}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./tooling/github-actions/install

      - name: Run Playwright tests
        run: turbo e2e --filter=IGNORED
        env:
          PLAYWRIGHT_USER_PASSWORD: ${{ secrets.PLAYWRIGHT_USER_PASSWORD }}
          PLAYWRIGHT_BASE_URL: ${{ inputs.deployment_url }}

      - name: Mark check complete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHECK_RUN_ID: ${{inputs.check_run_id}}
        run: pnpm --filter @kittr/github-actions exec vite-node scripts/mark-check-complete.ts
