name: Playwright - kittr
on:
  workflow_dispatch:
    inputs:
      deployment_url:
        required: true
        type: string
      check_run_id:
        required: true
        type: string

env:
  FORCE_COLOR: 3
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  web:
    name: 'Web'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./tooling/github-actions/install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: turbo e2e --filter=playwright-web
        env:
          PLAYWRIGHT_USER_PASSWORD: ${{ secrets.PLAYWRIGHT_USER_PASSWORD }}
          PLAYWRIGHT_BASE_URL: ${{ inputs.deployment_url }}

      - name: Mark check complete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHECK_RUN_ID: ${{inputs.check_run_id}}
        run: pnpm --filter @kittr/github-actions exec vite-node scripts/mark-check-complete.ts
