name: Playwright Testing
on:
  deployment_status:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.deployment_status.environment }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.0
        with:
          skip_after_successful_duplicate: 'true'

  design-react:
    name: 'Design (React)'
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./tooling/github-actions/install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run tests
        if: github.event.deployment_status.state == 'success' && contains(github.event.deployment_status.environment, 'design-react')
        run: turbo e2e --filter=IGNORED
        env:
          PLAYWRIGHT_USER_PASSWORD: ${{ secrets.PLAYWRIGHT_USER_PASSWORD }}
          PLAYWRIGHT_BASE_URL: ${{ github.event.deployment_status.target_url }}
