name: Playwright Testing
on:
  deployment_status:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.deployment_status.environment }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  web:
    name: 'Web'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./tooling/github-actions/install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run tests
        if: github.event.deployment_status.state == 'success' && contains(github.event.deployment_status.environment, 'kittr')
        run: turbo e2e --filter=playwright-web
        env:
          PLAYWRIGHT_USER_PASSWORD: ${{ secrets.PLAYWRIGHT_USER_PASSWORD }}
          PLAYWRIGHT_BASE_URL: ${{ github.event.deployment_status.target_url }}

      - name: Run Playwright tests
        if: github.event.deployment_status.state == 'success' && contains(github.event.deployment_status.environment, 'design-react')
        run: turbo e2e --filter=IGNORED
        env:
          PLAYWRIGHT_USER_PASSWORD: ${{ secrets.PLAYWRIGHT_USER_PASSWORD }}
          PLAYWRIGHT_BASE_URL: ${{ github.event.deployment_status.target_url }}
