name: Quality

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  FORCE_COLOR: 3
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  quality:
    name: Format + Lint + Typecheck
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./tooling/github-actions/install

      - name: Run Prettier
        run: turbo format lint typecheck --continue

  # eslint:
  #   name: ESLint
  #   timeout-minutes: 15
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Setup and install
  #       uses: ./tooling/github-actions/install

  #     - name: Lint
  #       run: turbo lint --continue

  # typecheck:
  #   name: TypeScript
  #   timeout-minutes: 15
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Install
  #       uses: ./tooling/github-actions/install

  #     - name: Run TypeScript type check
  #       run: turbo typecheck --continue
