name: Quality

on:
  push:
    branches:
      - master
  pull_request:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  FORCE_COLOR: 3
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  prettier:
    name: 'Prettier'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Commits made with the default `GITHUB_TOKEN` won't trigger workflows.
          # See: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
          # token: ${{ secrets.GH_TOKEN_REPO_SCOPE }}
          # We need to use the branch ref or we can't push fixes.
          ref: ${{ github.event.pull_request.head.ref || '' }}

      - name: Install
        uses: ./tooling/github-actions/composite-actions/install

      - name: Run Prettier (auto-fix)
        run: pnpm prettier-fix

      - name: Commit Prettier fixes
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No Prettier issues were found."
          else
            echo "The following files were modified by Prettier and will be updated on your branch:"
            git status --porcelain
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git commit -am "Apply Prettier fixes" --no-verify
            git push
          fi

  eslint:
    name: 'ESLint'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup and install
        uses: ./tooling/github-actions/install
      - name: Lint
        run: npx turbo run lint

  types:
    name: 'TypeScript'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./tooling/github-actions/install

      - name: Cache TypeScript TSBuild Info Files
        id: cache-typescript-tsbuildinfo
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/*-tsbuildinfo.json
          # We use the commit hash as the key to always update the cache as a
          # workaround to this issue:
          # https://github.com/actions/cache/issues/106
          key: ${{ runner.os }}-cache-typescript-tsbuildinfo-${{ github.sha }}
          restore-keys: ${{ runner.os }}-cache-typescript-tsbuildinfo-

      - name: Run TypeScript type check
        run: yarn type-check
