FROM node:16-alpine3.14

WORKDIR /app

# Installing dependencies
COPY package*.json ./
RUN npm install

# Copying source files
COPY ./ ./

# Expose the port
ENV PORT 3000

# Run in dev mode
CMD [ "npm", "run", "dev" ]